variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  SONAR_TOKEN: 7e63d6ff74e9b2be5a177a4eaa85dd09e3887272
  SONAR_HOST_URL: http://15.164.195.107:30087

check coverage: # Job name
  stage: build # Stage name
  image:
    name: docker.io/gradle:6.9.2-jdk8
    entrypoint: [""]
  script:
    - export
    - |
      if [[ ! -e gradle/wrapper/gradle-wrapper.jar ]]
      then
        gradle wrapper
      fi
    - chmod +x gradlew
    - ./gradlew sonarqube -Dsonar.qualitygate.wait=true -Dsonar.projectKey=$APP_NAME -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.sources=src/main/java -Dsonar.test=src/test/java -Dsonar.java.binaries=build/classes -Dsonar.inclusions=**/*Service.java -Dsonar.exclusions=src/main/java/org/paasta/container/platform/common/api/common/* --stacktrace
  allow_failure: true
  cache: # Artifact tag 사용 가능
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .sonar/cache
